-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product_table
(
    product_id bigserial NOT NULL,
    description character varying(150) NOT NULL,
    "price (in Rand)" numeric(7, 2) NOT NULL,
    PRIMARY KEY (product_id),
    CONSTRAINT description UNIQUE (description)
);

SELECT * FROM product_table;

INSERT INTO product_table (description, "price (in Rand)")
VALUES 
('Milk', 30.21),
('Sugar', 22.52),
('Bread', 19.99),
('Coca-cola', 26.99),
('Oxtail', 142.38)
;

CREATE TABLE IF NOT EXISTS public.cart_table
(
    product_id bigint NOT NULL,
    quantity numeric(4) NOT NULL CHECK ( quantity > -1) 
);

SELECT * FROM cart_table;

INSERT INTO cart_table (product_id, quantity)
VALUES 
(1,1),
(2,2),
(3,1),
(4,2),
(5,1)
;

-- Display Cart Table without update --
SELECT description, quantity, "price (in Rand)", quantity * "price (in Rand)" AS subtotal FROM cart_table
INNER JOIN product_table ON cart_table.product_id=product_table.product_id;


-- Update Cart_Table add 1 --
update cart_table set cart_table.quantity = cart_table.quantity+1 
where exists (SELECT * FROM cart_table  WHERE cart_table.product_id=5)--IF THIS PRODUCT EXISTS THEN THE UPDATE WILL BE DONE
and cart_table.product_id=5 ;
--SHOW CART
SELECT description, quantity, "price (in Rand)", quantity * "price (in Rand)" AS subtotal FROM cart_table
INNER JOIN product_table ON cart_table.product_id=product_table.product_id;


-- IF Quantity = 0 add product to Cart table --
insert into cart_table (product_id, quantity)
select 
    5,1
where not exists (
    select 1 from cart_table where product_id = 5);
--SHOW CART
SELECT description, quantity, "price (in Rand)", quantity * "price (in Rand)" AS subtotal FROM cart_table
INNER JOIN product_table ON cart_table.product_id=product_table.product_id;


-- Update Cart_Table remove 1 --
update cart_table set cart_table.quantity = cart_table.quantity -1 
where exists (SELECT * FROM cart_table  WHERE cart_table.product_id=3)--IF THIS PRODUCT EXISTS THEN THE UPDATE WILL BE DONE
and cart_table.product_id=3;
--SHOW CART
SELECT description, quantity, "price (in Rand)", quantity * "price (in Rand)" AS subtotal FROM cart_table
INNER JOIN product_table ON cart_table.product_id=product_table.product_id;


-- IF Quantity is 0 in cart--
DELETE FROM cart_table WHERE cart_table.quantity <= 0;
--SHOW CART
SELECT description, quantity, "price (in Rand)", quantity * "price (in Rand)" AS subtotal FROM cart_table
INNER JOIN product_table ON cart_table.product_id=product_table.product_id;


SELECT 
SUM(quantity) AS All_Products, 
SUM(cart_table.quantity * product_table."price (in Rand)" )AS GrandTotal FROM cart_table
INNER JOIN product_table ON product_table.product_id = cart_table.product_id;

ALTER TABLE IF EXISTS public.cart_table
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public.product_table (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;